### ISSUE TITLE
Reading Jpeg Metadata Very Slow

### ISSUE THREAD

**Issue by IanSC** [drewnoakes/metadata-extractor-images#18]
[Slowdown Sample.zip](https://github.com/drewnoakes/metadata-extractor-images/files/1670823/Slowdown.Sample.zip)

attached file, causes 20-30 secs delay when calling:

```
var directories = MetadataExtractor.ImageMetadataReader.ReadMetadata( pathFile );
```

tried using NuGet compiled libs, then source code, same result.
The Jpg file is big, but it should not matter, since it's a metadata extractor.

traced it to:
- call to JpegMetadataReader.ReadMetadata()
- calls Xmp.ReadJpegSegments()
- calls XmpNode in XmpCore project

```
private static XmpNode Find(IList<XmpNode> list, string expr)`
    => list?.FirstOrDefault(node => node.Name == expr);`

    "list" variable reaches 60,000+ count
    expr = "rdf:li" keeps getting added
```

- after it runs hit visual studio pause button to see
- also in Rdf_ResourcePropertyElement() ( ParseRdf.cs in XmpCore )
   just before it exits, the xml of "currChildElem" variable is over 3mb

Thanks,

**Comment by kwhopper** [comment]
@IanSC - thanks for the file. Are you able to provide a text file of just the embedded XMP? I extracted the binary data manually with a hex editor, but parsing that directly with XmpCore fails because of bad XMP.

**Comment by drewnoakes** [comment]
The Java library is susceptible to this too, outputting:

> Processed 5.036 MB file in 28513.26 ms

Seems like a problem with Adobe's XMPCore project. The Java version is maintained by Adobe so there might not be much we can do about that, but the .NET port is under our control so we can look at patching that one (which is the version you're using anyway).

https://github.com/drewnoakes/xmp-core-dotnet

I haven't had a chance to look deeply into this issue yet, but should do so soon.

**Comment by drewnoakes** [comment]
That JPEG contains 3,732,893 bytes of XMP.

It starts with:

```
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c138 79.159824, 2016/09/14-01:09:01        "> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/" photoshop:LegacyIPTCDigest="00000000000000000000000000000001" photoshop:ICCProfile="U.S. Web Coated (SWOP) v2" photoshop:ColorMode="4" xmpMM:OriginalDocumentID="xmp.did:42a65a62-490a-ba40-9b3d-4ffc87ca11f4" xmpMM:InstanceID="xmp.iid:4263d33e-1dab-1a4a-85f2-cc8cbc98f0b3" xmpMM:DocumentID="xmp.did:42a65a62-490a-ba40-9b3d-4ffc87ca11f4" xmp:CreatorTool="Adobe Photoshop CC 2017 (Windows)" xmp:MetadataDate="2017-07-23T01:03:26+08:00" xmp:CreateDate="2017-07-21T20:53:24+08:00" xmp:ModifyDate="2017-07-23T01:03:26+08:00" dc:format="image/jpeg"> <photoshop:DocumentAncestors> <rdf:Bag> <rdf:li>0</rdf:li> <rdf:li>000A05A484ECA8A35C739BCCEEF46BA0</rdf:li> <rdf:li>000B84DD32F5ABCC8D7B5E8681465EE9</rdf:li> <rdf:li>000CA3710D6B3CE061366A0D0396695D</rdf:li> <rdf:li>0013FA92942B6EC5451A4D9D4972AD7E</rdf:li> <rdf:li>0017ED7FA617555EF7D04797B72E2946</rdf:li> <rdf:li>002CC8540A72275EA014B42546B82315</rdf:li> <rdf:li>0030491E2F4C927C3D67B20A9710BC01</rdf:li> <rdf:li>003148FAF12A1DA304179B27E3ADEA69</rdf:li> <rdf:li>
```

Then there are a zillion `<rdf:li>` elements, all children of a single `<rdf:Bag>` element.

Finally it closes out with:

```
<rdf:li>xmp.id:1C0F5E963B8CE211A5CF892FFA4BA08A</rdf:li> <rdf:li>xmp.id:699C48C20720681183D1CA39AF2C8ACC</rdf:li> <rdf:li>xmp.id:7BABDED1072068118C14AF7F75CB8535</rdf:li> <rdf:li>xmp.id:B5B5C1B6562068118083EC41306B5EAE</rdf:li> <rdf:li>xmp.id:CF47CBFDB6E8E21185449207C312709E</rdf:li> <rdf:li>xmp.id:F19FA32829206811822AE20335FB17C9</rdf:li> </rdf:Bag> </photoshop:DocumentAncestors> <xmpMM:History> <rdf:Seq> <rdf:li stEvt:action="created" stEvt:instanceID="xmp.iid:42a65a62-490a-ba40-9b3d-4ffc87ca11f4" stEvt:when="2017-07-21T20:53:24+08:00" stEvt:softwareAgent="Adobe Photoshop CC 2017 (Windows)"/> <rdf:li stEvt:action="saved" stEvt:instanceID="xmp.iid:4263d33e-1dab-1a4a-85f2-cc8cbc98f0b3" stEvt:when="2017-07-23T01:03:26+08:00" stEvt:softwareAgent="Adobe Photoshop CC 2017 (Windows)" stEvt:changed="/"/> </rdf:Seq> </xmpMM:History> </rdf:Description> </rdf:RDF> </x:xmpmeta> 
```

This blows out performance on the O(N) code used to ensure a name is not present. One potential solution is to modify `XmpNode` to add an associative collection (dictionary) with O(1) lookup characteristics alongside the current `List<XmpNode> _children` field. I haven't looked deeply into whether this would cause other problems though.

DotTrace shows the bulk of the time is spent doing the O(N) scan using Linq's `FirstOrDefault` with a lambda:

![image](https://user-images.githubusercontent.com/350947/35529982-9f124090-052a-11e8-878e-e516662b7b9b.png)

**Comment by drewnoakes** [comment]
@kwhopper's fix to the XMP project has eradicated this problem.

I'll get a new version of MetadataExtractor out shortly.

**Comment by IanSC** [comment]
Thanks for the fix. Never knew there was a something amiss until you pointed it out.

It seems it's a common problem:
https://forums.adobe.com/thread/2081839
http://prepression.blogspot.com/2017/06/metadata-bloat-photoshopdocumentancestors.html

Here's the link on how to remove excess "DocumentAncestor" in the XMP:
http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,8247.0.html

My originally attached file got reduced from 5 mb to 1.5mb.
Did some rough benchmarks:

Old version MetadataExtractor 2.0.0 / XMPCore 5.1.3.1:
Orig 5mb = 121.87 sec
Diet 1.5mb = 0.35 sec 

New version MetadataExtractor 2.0.0 / XMPCore 6.1.10.0
Orig 5mb = 0.99 sec
Diet 1.5mb = 0.27 sec

Thanks again.

Request: Please add support on extracting just the raw XMP test from Adobe Illustrator (*.ai, *.pdf),
Photoshop (*.psd, *.psb) and InDesign (*.indd). Don't know where to post request at it's definitely not an issue/problem.

**Comment by IanSC** [comment]
> @IanSC - thanks for the file. Are you able to provide a text file of just the embedded XMP? I extracted the binary data manually with a hex editor, but parsing that directly with XmpCore fails because of bad XMP.

@kwhopper 
Sorry, newbie here. Didn't mean to ignore it. I do not have the XMP as the file was generated using Photoshop. Thanks for the help!

**Comment by IanSC** [comment]
[Slowdown Sample.zip](https://github.com/drewnoakes/metadata-extractor-images/files/2441579/Slowdown.Sample.zip)

@kwhopper 
Just in case it is still relevant. Got this from Photoshop, using:
1. open file / 2. Menu: File -> FileInfo... / 3. Raw Data tab / 4. Export
