### ISSUE TITLE
Add samples of Sony ILCE-7M3 (A7M3)

### ISSUE THREAD

**Issue by patricksadowski** [drewnoakes/metadata-extractor-images#25]
[Here](https://1drv.ms/f/s!As0MXM0pYqXio1QCRESrb1i1A2Pt) you can find some sample images and videos of the mentioned camera. When the issue is closed I'll remove the samples from my cloud storage.

**Comment by drewnoakes** [comment]
Thank you very much for these. Feel free to delete from your OneDrive.
