### ISSUE TITLE
Showing Wrong metadata info for width and height 

### ISSUE THREAD

**Issue by gkteck** [drewnoakes/metadata-extractor-images#26]
I am using version 2.12.0, For some images, it is showing the wrong value for height and width under jpegDirectory metadata.

[JPEG] - Compression Type = Baseline
[JPEG] - Data Precision = 8 bits
**[JPEG] - Image Height = 2000 pixels
[JPEG] - Image Width = 3000 pixels**
[JPEG] - Number of Components = 3

In this case the actual image Height = 3000 pixels and Width = 2000 pixels.
I can send the image in email.

**Comment by drewnoakes** [comment]
Are you using the Java or .NET implementation?

Please try and attach the issue here, or use wetransfer/mega/etc to make a link available.

My guess is that the height/width are transposed due to the image's orientation.

**Comment by gkteck** [comment]
Hi,
I finally found out the issue, all the portrait shoots were 90 degrees rotated. So the framework is fine. I just needed to check the image orientation to handle this.
