### ISSUE TITLE
Need CRX/CR3 sample images

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor-images#28]
For coverage of capabilities added in https://github.com/drewnoakes/metadata-extractor-dotnet/pull/205.

**Comment by thorsted** [comment]
Feel free to use my images. https://github.com/thorsted/digicam_corpus/tree/master/Canon/EOS%20RP

**Comment by drewnoakes** [comment]
@thorsted wow, you have a great selection of media. Are these images directly from the camera?

We use the data in this repo to track the output of both the Java and .NET implementations of the library over time, to compare for parity, recognise improvements, and prevent regressions.

Would you have any problem with us hosting your entire repo as a submodule here? We would need to store the metadata files in this repo directly.

**Comment by thorsted** [comment]
@drewnoakes yes, all files are direct camera images taken by myself from my collection. Feel free to use however is most helpful. Let me know if there are additional images needed.

**Comment by drewnoakes** [comment]
I've integrated @thorsted's data to the repo. Thanks again!
