### ISSUE TITLE
DJI Mavic 3 Drone Photos with Rotational and Velocity Data

### ISSUE THREAD

**Issue by JoshuaNeilCoady** [drewnoakes/metadata-extractor-images#44]
![DJI_0252](https://github.com/drewnoakes/metadata-extractor-images/assets/117324971/c37a9590-15a9-4f72-8f53-2b5981c28638)

**Comment by drewnoakes** [comment]
Thanks very much. I've uploaded this sample image along with the metadata we currently extract. The flight data is present in the XMP segment.
